apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: hbkw1772/goorm-project:54
        name: flaskdemo
        resources: {}
        volumeMounts:
        - name: aws-sc-ebs-pvc-db
          mountPath: /data
      volumes:
      - name: aws-sc-ebs-pvc-db
        persistentVolumeClaim:
          claimName: aws-sc-ebs-pvc
          
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
