apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: hbkw1772/goorm-project:35
        name: flaskdemo
        volumeMounts:
        - name: flask-db
          mountPath: /goorm-jenkins
        resources: {}
      volumes:
      - name: flask-db
        hostPath:
          path: /var/lib/docker/volumes/test/_data 
          type: DirectoryOrCreate
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
